dist: trusty

os: windows

language: shell

matrix:
  include:

  - name: "MSVC on Windows"
    os: windows
    script:
    - choco install meson -y
    - choco install nasm -y # installs cmake as dep
    #- choco install cmake -y
    - choco install activeperl -y
    - Update-SessionEnvironment

    - cmd.exe /C '"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" amd64 && build-win.bat'