dist: trusty

os: windows

language: shell

matrix:
  include:

  - name: "MSVC on Windows"
    os: windows
    install:
      - choco install -y meson
      - choco install -y nasm # installs cmake as dep
      #- choco install -y cmake
      - choco install -y activeperl
    script:
    - cmd.exe /C '"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" amd64 && build-openh264.bat'
    - cmd.exe /C '"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" amd64 && build-openssl.bat'
    - cmd.exe /C '"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" amd64 && build-win.bat'

cache:
  - directories:
      - deps